### ISSUE TITLE
Work for Sonia Narayanan

### ISSUE THREAD

**Issue by jakep11** [cpe305/fall2016-project-jakep11#1]
@sonianara Please make a java class for TriathlonTime. 

Attributes
- swimTime: time
- t1Time: time
- bikeTime: time
- t2Time: time
- runTime: time

Methods:
- getters and setters for all 5 above
- getTotalTime()

**Comment by sonianara** [comment]
I created a Time class as well to make it easier to calculate the total time

**Comment by jakep11** [comment]
@sonianara For future reference add .DS_Store to the .gitignore file so that you don't check in .DS_Store to the GitHub Repo :)
